server:
  applicationConnectors:
    - type: http
      port: 12090
  adminConnectors:
    - type: http
      port: 12091

database:
  driverClass: org.postgresql.Driver
  user: irm_user
  password: hermitcrab
  url: jdbc:postgresql://localhost:5432/irm_user_db
  properties:
    charset: utf-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1;"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  evictionInterval: 10s
  minIdleTime: 1 minute

authConfig:
  authUsers:
    - name: admin
      role: svc-admin
      password: wdx908okp2
    - name: client
      role: svc-client
      password: test123
